name: First Workflow
on: [push]
jobs:
  job1-runs-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: step1 echo
        run: echo "Hello"
      - name: step2 run-multiple
        run: |
          mvn -v
          java --version
      - name: step3 python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  job2-runs-windows-commands-job:
    runs-on: windows-latest
    needs: [job1-runs-shell-command]
    steps:
        - name: step1 Directory Powershell
          run: Get-Location
        - name: step 2Directory Bash
          run: pwd
          shell: bash

          
