name: first workflow
on: [push]
jobs:
  runs-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello"
      - name: run-multiple
        run: |
          mvn -v
          java --version
          
